// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePickerAssignment = `-- name: DeletePickerAssignment :exec
DELETE FROM _deprecated_picker_assignments WHERE group_id = $1 AND week_of = $2
`

type DeletePickerAssignmentParams struct {
	GroupID int32  `json:"group_id"`
	WeekOf  string `json:"week_of"`
}

func (q *Queries) DeletePickerAssignment(ctx context.Context, arg DeletePickerAssignmentParams) error {
	_, err := q.db.Exec(ctx, deletePickerAssignment, arg.GroupID, arg.WeekOf)
	return err
}

const getPickerAssignment = `-- name: GetPickerAssignment :one
SELECT id, group_id, user_id, week_of
FROM _deprecated_picker_assignments
WHERE group_id = $1 AND week_of = $2
`

type GetPickerAssignmentParams struct {
	GroupID int32  `json:"group_id"`
	WeekOf  string `json:"week_of"`
}

type GetPickerAssignmentRow struct {
	ID      int32  `json:"id"`
	GroupID int32  `json:"group_id"`
	UserID  int32  `json:"user_id"`
	WeekOf  string `json:"week_of"`
}

func (q *Queries) GetPickerAssignment(ctx context.Context, arg GetPickerAssignmentParams) (GetPickerAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getPickerAssignment, arg.GroupID, arg.WeekOf)
	var i GetPickerAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.WeekOf,
	)
	return i, err
}

const getPickerAssignmentsForGroup = `-- name: GetPickerAssignmentsForGroup :many
SELECT pa.group_id, pa.user_id, pa.week_of, u.username AS picker_username
FROM _deprecated_picker_assignments pa
JOIN users u ON u.id = pa.user_id
WHERE pa.group_id = $1
ORDER BY pa.week_of
`

type GetPickerAssignmentsForGroupRow struct {
	GroupID        int32  `json:"group_id"`
	UserID         int32  `json:"user_id"`
	WeekOf         string `json:"week_of"`
	PickerUsername string `json:"picker_username"`
}

func (q *Queries) GetPickerAssignmentsForGroup(ctx context.Context, groupID int32) ([]GetPickerAssignmentsForGroupRow, error) {
	rows, err := q.db.Query(ctx, getPickerAssignmentsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPickerAssignmentsForGroupRow{}
	for rows.Next() {
		var i GetPickerAssignmentsForGroupRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.WeekOf,
			&i.PickerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTurnExtensions = `-- name: GetTurnExtensions :many
SELECT id, group_id, turn_index, extra_days
FROM _deprecated_turn_extensions
WHERE group_id = $1
`

type GetTurnExtensionsRow struct {
	ID        int32 `json:"id"`
	GroupID   int32 `json:"group_id"`
	TurnIndex int32 `json:"turn_index"`
	ExtraDays int32 `json:"extra_days"`
}

func (q *Queries) GetTurnExtensions(ctx context.Context, groupID int32) ([]GetTurnExtensionsRow, error) {
	rows, err := q.db.Query(ctx, getTurnExtensions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTurnExtensionsRow{}
	for rows.Next() {
		var i GetTurnExtensionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.TurnIndex,
			&i.ExtraDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTurnOverride = `-- name: GetTurnOverride :one
SELECT id, group_id, week_of, review_unlocked_by_admin, movie_unlocked_by_admin, extended_days, start_offset_days, updated_at
FROM _deprecated_turn_overrides
WHERE group_id = $1 AND week_of = $2
`

type GetTurnOverrideParams struct {
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

type GetTurnOverrideRow struct {
	ID                    int32       `json:"id"`
	GroupID               int32       `json:"group_id"`
	WeekOf                pgtype.Date `json:"week_of"`
	ReviewUnlockedByAdmin bool        `json:"review_unlocked_by_admin"`
	MovieUnlockedByAdmin  bool        `json:"movie_unlocked_by_admin"`
	ExtendedDays          int32       `json:"extended_days"`
	StartOffsetDays       int32       `json:"start_offset_days"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

func (q *Queries) GetTurnOverride(ctx context.Context, arg GetTurnOverrideParams) (GetTurnOverrideRow, error) {
	row := q.db.QueryRow(ctx, getTurnOverride, arg.GroupID, arg.WeekOf)
	var i GetTurnOverrideRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.WeekOf,
		&i.ReviewUnlockedByAdmin,
		&i.MovieUnlockedByAdmin,
		&i.ExtendedDays,
		&i.StartOffsetDays,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurnOverridesForGroup = `-- name: GetTurnOverridesForGroup :many
SELECT id, group_id, week_of, review_unlocked_by_admin, movie_unlocked_by_admin, extended_days, start_offset_days, updated_at
FROM _deprecated_turn_overrides
WHERE group_id = $1
ORDER BY week_of
`

type GetTurnOverridesForGroupRow struct {
	ID                    int32       `json:"id"`
	GroupID               int32       `json:"group_id"`
	WeekOf                pgtype.Date `json:"week_of"`
	ReviewUnlockedByAdmin bool        `json:"review_unlocked_by_admin"`
	MovieUnlockedByAdmin  bool        `json:"movie_unlocked_by_admin"`
	ExtendedDays          int32       `json:"extended_days"`
	StartOffsetDays       int32       `json:"start_offset_days"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

func (q *Queries) GetTurnOverridesForGroup(ctx context.Context, groupID int32) ([]GetTurnOverridesForGroupRow, error) {
	rows, err := q.db.Query(ctx, getTurnOverridesForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTurnOverridesForGroupRow{}
	for rows.Next() {
		var i GetTurnOverridesForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.WeekOf,
			&i.ReviewUnlockedByAdmin,
			&i.MovieUnlockedByAdmin,
			&i.ExtendedDays,
			&i.StartOffsetDays,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPickerAssignment = `-- name: UpsertPickerAssignment :exec

INSERT INTO _deprecated_picker_assignments (group_id, user_id, week_of)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT picker_group_week_unique
DO UPDATE SET user_id = EXCLUDED.user_id
`

type UpsertPickerAssignmentParams struct {
	GroupID int32  `json:"group_id"`
	UserID  int32  `json:"user_id"`
	WeekOf  string `json:"week_of"`
}

// Queries for legacy turn management tables (deprecated).
// These reference the renamed _deprecated_* tables.
// TODO: Remove once handlers are fully migrated to turns table.
func (q *Queries) UpsertPickerAssignment(ctx context.Context, arg UpsertPickerAssignmentParams) error {
	_, err := q.db.Exec(ctx, upsertPickerAssignment, arg.GroupID, arg.UserID, arg.WeekOf)
	return err
}

const upsertTurnExtension = `-- name: UpsertTurnExtension :exec
INSERT INTO _deprecated_turn_extensions (group_id, turn_index, extra_days)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT turn_extensions_group_turn_unique
DO UPDATE SET extra_days = EXCLUDED.extra_days
`

type UpsertTurnExtensionParams struct {
	GroupID   int32 `json:"group_id"`
	TurnIndex int32 `json:"turn_index"`
	ExtraDays int32 `json:"extra_days"`
}

func (q *Queries) UpsertTurnExtension(ctx context.Context, arg UpsertTurnExtensionParams) error {
	_, err := q.db.Exec(ctx, upsertTurnExtension, arg.GroupID, arg.TurnIndex, arg.ExtraDays)
	return err
}

const upsertTurnOverride = `-- name: UpsertTurnOverride :exec
INSERT INTO _deprecated_turn_overrides (group_id, week_of, review_unlocked_by_admin, movie_unlocked_by_admin, extended_days)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ON CONSTRAINT turn_overrides_group_week_unique
DO UPDATE SET review_unlocked_by_admin = EXCLUDED.review_unlocked_by_admin,
             movie_unlocked_by_admin = EXCLUDED.movie_unlocked_by_admin,
             extended_days = EXCLUDED.extended_days,
             updated_at = now()
`

type UpsertTurnOverrideParams struct {
	GroupID               int32       `json:"group_id"`
	WeekOf                pgtype.Date `json:"week_of"`
	ReviewUnlockedByAdmin bool        `json:"review_unlocked_by_admin"`
	MovieUnlockedByAdmin  bool        `json:"movie_unlocked_by_admin"`
	ExtendedDays          int32       `json:"extended_days"`
}

func (q *Queries) UpsertTurnOverride(ctx context.Context, arg UpsertTurnOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertTurnOverride,
		arg.GroupID,
		arg.WeekOf,
		arg.ReviewUnlockedByAdmin,
		arg.MovieUnlockedByAdmin,
		arg.ExtendedDays,
	)
	return err
}

const upsertTurnOverrideExtendedDays = `-- name: UpsertTurnOverrideExtendedDays :one
INSERT INTO _deprecated_turn_overrides (group_id, week_of, extended_days)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT turn_overrides_group_week_unique
DO UPDATE SET extended_days = EXCLUDED.extended_days, updated_at = now()
RETURNING id, group_id, week_of, review_unlocked_by_admin, movie_unlocked_by_admin, extended_days, start_offset_days, updated_at
`

type UpsertTurnOverrideExtendedDaysParams struct {
	GroupID      int32       `json:"group_id"`
	WeekOf       pgtype.Date `json:"week_of"`
	ExtendedDays int32       `json:"extended_days"`
}

type UpsertTurnOverrideExtendedDaysRow struct {
	ID                    int32       `json:"id"`
	GroupID               int32       `json:"group_id"`
	WeekOf                pgtype.Date `json:"week_of"`
	ReviewUnlockedByAdmin bool        `json:"review_unlocked_by_admin"`
	MovieUnlockedByAdmin  bool        `json:"movie_unlocked_by_admin"`
	ExtendedDays          int32       `json:"extended_days"`
	StartOffsetDays       int32       `json:"start_offset_days"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

func (q *Queries) UpsertTurnOverrideExtendedDays(ctx context.Context, arg UpsertTurnOverrideExtendedDaysParams) (UpsertTurnOverrideExtendedDaysRow, error) {
	row := q.db.QueryRow(ctx, upsertTurnOverrideExtendedDays, arg.GroupID, arg.WeekOf, arg.ExtendedDays)
	var i UpsertTurnOverrideExtendedDaysRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.WeekOf,
		&i.ReviewUnlockedByAdmin,
		&i.MovieUnlockedByAdmin,
		&i.ExtendedDays,
		&i.StartOffsetDays,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTurnOverrideMovieUnlocked = `-- name: UpsertTurnOverrideMovieUnlocked :exec
INSERT INTO _deprecated_turn_overrides (group_id, week_of, movie_unlocked_by_admin)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT turn_overrides_group_week_unique
DO UPDATE SET movie_unlocked_by_admin = EXCLUDED.movie_unlocked_by_admin, updated_at = now()
`

type UpsertTurnOverrideMovieUnlockedParams struct {
	GroupID              int32       `json:"group_id"`
	WeekOf               pgtype.Date `json:"week_of"`
	MovieUnlockedByAdmin bool        `json:"movie_unlocked_by_admin"`
}

func (q *Queries) UpsertTurnOverrideMovieUnlocked(ctx context.Context, arg UpsertTurnOverrideMovieUnlockedParams) error {
	_, err := q.db.Exec(ctx, upsertTurnOverrideMovieUnlocked, arg.GroupID, arg.WeekOf, arg.MovieUnlockedByAdmin)
	return err
}

const upsertTurnOverrideReviewUnlocked = `-- name: UpsertTurnOverrideReviewUnlocked :exec
INSERT INTO _deprecated_turn_overrides (group_id, week_of, review_unlocked_by_admin)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT turn_overrides_group_week_unique
DO UPDATE SET review_unlocked_by_admin = EXCLUDED.review_unlocked_by_admin, updated_at = now()
`

type UpsertTurnOverrideReviewUnlockedParams struct {
	GroupID               int32       `json:"group_id"`
	WeekOf                pgtype.Date `json:"week_of"`
	ReviewUnlockedByAdmin bool        `json:"review_unlocked_by_admin"`
}

func (q *Queries) UpsertTurnOverrideReviewUnlocked(ctx context.Context, arg UpsertTurnOverrideReviewUnlockedParams) error {
	_, err := q.db.Exec(ctx, upsertTurnOverrideReviewUnlocked, arg.GroupID, arg.WeekOf, arg.ReviewUnlockedByAdmin)
	return err
}

const upsertTurnOverrideStartOffset = `-- name: UpsertTurnOverrideStartOffset :one
INSERT INTO _deprecated_turn_overrides (group_id, week_of, start_offset_days)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT turn_overrides_group_week_unique
DO UPDATE SET start_offset_days = EXCLUDED.start_offset_days, updated_at = now()
RETURNING id, group_id, week_of, review_unlocked_by_admin, movie_unlocked_by_admin, extended_days, start_offset_days, updated_at
`

type UpsertTurnOverrideStartOffsetParams struct {
	GroupID         int32       `json:"group_id"`
	WeekOf          pgtype.Date `json:"week_of"`
	StartOffsetDays int32       `json:"start_offset_days"`
}

type UpsertTurnOverrideStartOffsetRow struct {
	ID                    int32       `json:"id"`
	GroupID               int32       `json:"group_id"`
	WeekOf                pgtype.Date `json:"week_of"`
	ReviewUnlockedByAdmin bool        `json:"review_unlocked_by_admin"`
	MovieUnlockedByAdmin  bool        `json:"movie_unlocked_by_admin"`
	ExtendedDays          int32       `json:"extended_days"`
	StartOffsetDays       int32       `json:"start_offset_days"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

func (q *Queries) UpsertTurnOverrideStartOffset(ctx context.Context, arg UpsertTurnOverrideStartOffsetParams) (UpsertTurnOverrideStartOffsetRow, error) {
	row := q.db.QueryRow(ctx, upsertTurnOverrideStartOffset, arg.GroupID, arg.WeekOf, arg.StartOffsetDays)
	var i UpsertTurnOverrideStartOffsetRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.WeekOf,
		&i.ReviewUnlockedByAdmin,
		&i.MovieUnlockedByAdmin,
		&i.ExtendedDays,
		&i.StartOffsetDays,
		&i.UpdatedAt,
	)
	return i, err
}
