// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPickerAssignment = `-- name: GetPickerAssignment :one

SELECT t.id, t.group_id, t.picker_user_id AS user_id,
       to_char(t.week_of, 'YYYY-MM-DD') AS week_of
FROM turns t
WHERE t.group_id = $1
  AND t.week_of = $2::date
`

type GetPickerAssignmentParams struct {
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

type GetPickerAssignmentRow struct {
	ID      int64  `json:"id"`
	GroupID int32  `json:"group_id"`
	UserID  int32  `json:"user_id"`
	WeekOf  string `json:"week_of"`
}

// Picker assignment, turn override, and turn extension queries are thin views
// over the canonical turns table. Each turn owns its own picker, schedule
// (start_date / end_date), and admin unlocks (movie_unlocked / reviews_unlocked).
// Legacy concepts (`extended_days`, `start_offset_days`, per-index extra_days)
// are derived on read and translated into direct turn updates on write.
func (q *Queries) GetPickerAssignment(ctx context.Context, arg GetPickerAssignmentParams) (GetPickerAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getPickerAssignment, arg.GroupID, arg.WeekOf)
	var i GetPickerAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.WeekOf,
	)
	return i, err
}

const getPickerAssignmentsForGroup = `-- name: GetPickerAssignmentsForGroup :many
SELECT t.group_id,
       t.picker_user_id AS user_id,
       to_char(t.week_of, 'YYYY-MM-DD') AS week_of,
       u.username AS picker_username
FROM turns t
JOIN users u ON u.id = t.picker_user_id
WHERE t.group_id = $1
ORDER BY t.week_of
`

type GetPickerAssignmentsForGroupRow struct {
	GroupID        int32  `json:"group_id"`
	UserID         int32  `json:"user_id"`
	WeekOf         string `json:"week_of"`
	PickerUsername string `json:"picker_username"`
}

func (q *Queries) GetPickerAssignmentsForGroup(ctx context.Context, groupID int32) ([]GetPickerAssignmentsForGroupRow, error) {
	rows, err := q.db.Query(ctx, getPickerAssignmentsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPickerAssignmentsForGroupRow{}
	for rows.Next() {
		var i GetPickerAssignmentsForGroupRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.WeekOf,
			&i.PickerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTurnExtensions = `-- name: GetTurnExtensions :many
SELECT t.id,
       t.group_id,
       t.turn_index,
       (t.end_date - t.start_date + 1 - g.turn_length_days)::int AS extra_days
FROM turns t
JOIN groups g ON g.id = t.group_id
WHERE t.group_id = $1
  AND (t.end_date - t.start_date + 1 - g.turn_length_days) > 0
ORDER BY t.turn_index
`

type GetTurnExtensionsRow struct {
	ID        int64 `json:"id"`
	GroupID   int32 `json:"group_id"`
	TurnIndex int32 `json:"turn_index"`
	ExtraDays int32 `json:"extra_days"`
}

// Returns combined per-turn extra days (turn-extension + override-extended) for
// each turn whose effective length exceeds the group's base turn_length_days.
func (q *Queries) GetTurnExtensions(ctx context.Context, groupID int32) ([]GetTurnExtensionsRow, error) {
	rows, err := q.db.Query(ctx, getTurnExtensions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTurnExtensionsRow{}
	for rows.Next() {
		var i GetTurnExtensionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.TurnIndex,
			&i.ExtraDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTurnOverride = `-- name: GetTurnOverride :one
SELECT t.id,
       t.group_id,
       t.week_of,
       t.reviews_unlocked AS review_unlocked_by_admin,
       t.movie_unlocked   AS movie_unlocked_by_admin,
       (t.end_date - t.start_date + 1 - g.turn_length_days)::int AS extended_days,
       (t.start_date - t.week_of)::int                            AS start_offset_days,
       t.updated_at
FROM turns t
JOIN groups g ON g.id = t.group_id
WHERE t.group_id = $1
  AND t.week_of = $2::date
`

type GetTurnOverrideParams struct {
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

type GetTurnOverrideRow struct {
	ID                    int64              `json:"id"`
	GroupID               int32              `json:"group_id"`
	WeekOf                pgtype.Date        `json:"week_of"`
	ReviewUnlockedByAdmin bool               `json:"review_unlocked_by_admin"`
	MovieUnlockedByAdmin  bool               `json:"movie_unlocked_by_admin"`
	ExtendedDays          int32              `json:"extended_days"`
	StartOffsetDays       int32              `json:"start_offset_days"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTurnOverride(ctx context.Context, arg GetTurnOverrideParams) (GetTurnOverrideRow, error) {
	row := q.db.QueryRow(ctx, getTurnOverride, arg.GroupID, arg.WeekOf)
	var i GetTurnOverrideRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.WeekOf,
		&i.ReviewUnlockedByAdmin,
		&i.MovieUnlockedByAdmin,
		&i.ExtendedDays,
		&i.StartOffsetDays,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurnOverridesForGroup = `-- name: GetTurnOverridesForGroup :many
SELECT t.id,
       t.group_id,
       t.week_of,
       t.reviews_unlocked AS review_unlocked_by_admin,
       t.movie_unlocked   AS movie_unlocked_by_admin,
       (t.end_date - t.start_date + 1 - g.turn_length_days)::int AS extended_days,
       (t.start_date - t.week_of)::int                            AS start_offset_days,
       t.updated_at
FROM turns t
JOIN groups g ON g.id = t.group_id
WHERE t.group_id = $1
ORDER BY t.week_of
`

type GetTurnOverridesForGroupRow struct {
	ID                    int64              `json:"id"`
	GroupID               int32              `json:"group_id"`
	WeekOf                pgtype.Date        `json:"week_of"`
	ReviewUnlockedByAdmin bool               `json:"review_unlocked_by_admin"`
	MovieUnlockedByAdmin  bool               `json:"movie_unlocked_by_admin"`
	ExtendedDays          int32              `json:"extended_days"`
	StartOffsetDays       int32              `json:"start_offset_days"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTurnOverridesForGroup(ctx context.Context, groupID int32) ([]GetTurnOverridesForGroupRow, error) {
	rows, err := q.db.Query(ctx, getTurnOverridesForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTurnOverridesForGroupRow{}
	for rows.Next() {
		var i GetTurnOverridesForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.WeekOf,
			&i.ReviewUnlockedByAdmin,
			&i.MovieUnlockedByAdmin,
			&i.ExtendedDays,
			&i.StartOffsetDays,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTurnExtension = `-- name: UpsertTurnExtension :exec
UPDATE turns t
SET end_date = t.start_date + (g.turn_length_days - 1 + $1::int),
    updated_at = now()
FROM groups g
WHERE g.id = t.group_id
  AND t.group_id = $2
  AND t.turn_index = $3
`

type UpsertTurnExtensionParams struct {
	ExtraDays int32 `json:"extra_days"`
	GroupID   int32 `json:"group_id"`
	TurnIndex int32 `json:"turn_index"`
}

func (q *Queries) UpsertTurnExtension(ctx context.Context, arg UpsertTurnExtensionParams) error {
	_, err := q.db.Exec(ctx, upsertTurnExtension, arg.ExtraDays, arg.GroupID, arg.TurnIndex)
	return err
}

const upsertTurnOverrideExtendedDays = `-- name: UpsertTurnOverrideExtendedDays :exec
UPDATE turns t
SET end_date = t.start_date + (g.turn_length_days - 1 + $1::int),
    updated_at = now()
FROM groups g
WHERE g.id = t.group_id
  AND t.group_id = $2
  AND t.week_of = $3::date
`

type UpsertTurnOverrideExtendedDaysParams struct {
	ExtendedDays int32       `json:"extended_days"`
	GroupID      int32       `json:"group_id"`
	WeekOf       pgtype.Date `json:"week_of"`
}

func (q *Queries) UpsertTurnOverrideExtendedDays(ctx context.Context, arg UpsertTurnOverrideExtendedDaysParams) error {
	_, err := q.db.Exec(ctx, upsertTurnOverrideExtendedDays, arg.ExtendedDays, arg.GroupID, arg.WeekOf)
	return err
}

const upsertTurnOverrideMovieUnlocked = `-- name: UpsertTurnOverrideMovieUnlocked :exec
UPDATE turns
SET movie_unlocked = $1, updated_at = now()
WHERE group_id = $2
  AND week_of = $3::date
`

type UpsertTurnOverrideMovieUnlockedParams struct {
	MovieUnlockedByAdmin bool        `json:"movie_unlocked_by_admin"`
	GroupID              int32       `json:"group_id"`
	WeekOf               pgtype.Date `json:"week_of"`
}

func (q *Queries) UpsertTurnOverrideMovieUnlocked(ctx context.Context, arg UpsertTurnOverrideMovieUnlockedParams) error {
	_, err := q.db.Exec(ctx, upsertTurnOverrideMovieUnlocked, arg.MovieUnlockedByAdmin, arg.GroupID, arg.WeekOf)
	return err
}

const upsertTurnOverrideReviewUnlocked = `-- name: UpsertTurnOverrideReviewUnlocked :exec
UPDATE turns
SET reviews_unlocked = $1, updated_at = now()
WHERE group_id = $2
  AND week_of = $3::date
`

type UpsertTurnOverrideReviewUnlockedParams struct {
	ReviewUnlockedByAdmin bool        `json:"review_unlocked_by_admin"`
	GroupID               int32       `json:"group_id"`
	WeekOf                pgtype.Date `json:"week_of"`
}

func (q *Queries) UpsertTurnOverrideReviewUnlocked(ctx context.Context, arg UpsertTurnOverrideReviewUnlockedParams) error {
	_, err := q.db.Exec(ctx, upsertTurnOverrideReviewUnlocked, arg.ReviewUnlockedByAdmin, arg.GroupID, arg.WeekOf)
	return err
}

const upsertTurnOverrideStartOffset = `-- name: UpsertTurnOverrideStartOffset :exec
UPDATE turns
SET start_date = week_of + $1::int,
    end_date   = (week_of + $1::int) + (end_date - start_date),
    updated_at = now()
WHERE group_id = $2
  AND week_of = $3::date
`

type UpsertTurnOverrideStartOffsetParams struct {
	StartOffsetDays int32       `json:"start_offset_days"`
	GroupID         int32       `json:"group_id"`
	WeekOf          pgtype.Date `json:"week_of"`
}

// Shifts the turn's start_date to (week_of + start_offset_days) while preserving
// the existing turn length (end_date - start_date stays constant).
func (q *Queries) UpsertTurnOverrideStartOffset(ctx context.Context, arg UpsertTurnOverrideStartOffsetParams) error {
	_, err := q.db.Exec(ctx, upsertTurnOverrideStartOffset, arg.StartOffsetDays, arg.GroupID, arg.WeekOf)
	return err
}
