// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: films.sql

package db

import (
	"context"
)

const getFilmByID = `-- name: GetFilmByID :one
SELECT id, imdb_id, title, year, poster_url, director, genre, runtime_minutes, omdb_fetched_at, created_at
FROM films
WHERE id = $1
`

func (q *Queries) GetFilmByID(ctx context.Context, id int64) (Film, error) {
	row := q.db.QueryRow(ctx, getFilmByID, id)
	var i Film
	err := row.Scan(
		&i.ID,
		&i.ImdbID,
		&i.Title,
		&i.Year,
		&i.PosterUrl,
		&i.Director,
		&i.Genre,
		&i.RuntimeMinutes,
		&i.OmdbFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFilmByIMDbID = `-- name: GetFilmByIMDbID :one
SELECT id, imdb_id, title, year, poster_url, director, genre, runtime_minutes, omdb_fetched_at, created_at
FROM films
WHERE imdb_id = $1
`

func (q *Queries) GetFilmByIMDbID(ctx context.Context, imdbID string) (Film, error) {
	row := q.db.QueryRow(ctx, getFilmByIMDbID, imdbID)
	var i Film
	err := row.Scan(
		&i.ID,
		&i.ImdbID,
		&i.Title,
		&i.Year,
		&i.PosterUrl,
		&i.Director,
		&i.Genre,
		&i.RuntimeMinutes,
		&i.OmdbFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const searchFilmsByTitle = `-- name: SearchFilmsByTitle :many
SELECT id, imdb_id, title, year, poster_url, director, genre, runtime_minutes, omdb_fetched_at, created_at
FROM films
WHERE title ILIKE '%' || $1 || '%'
ORDER BY title
LIMIT $2
`

type SearchFilmsByTitleParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
}

func (q *Queries) SearchFilmsByTitle(ctx context.Context, arg SearchFilmsByTitleParams) ([]Film, error) {
	rows, err := q.db.Query(ctx, searchFilmsByTitle, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Film{}
	for rows.Next() {
		var i Film
		if err := rows.Scan(
			&i.ID,
			&i.ImdbID,
			&i.Title,
			&i.Year,
			&i.PosterUrl,
			&i.Director,
			&i.Genre,
			&i.RuntimeMinutes,
			&i.OmdbFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFilm = `-- name: UpsertFilm :one
INSERT INTO films (imdb_id, title, year, poster_url, director, genre, runtime_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (imdb_id)
DO UPDATE SET
    title = EXCLUDED.title,
    year = EXCLUDED.year,
    poster_url = EXCLUDED.poster_url,
    director = EXCLUDED.director,
    genre = EXCLUDED.genre,
    runtime_minutes = EXCLUDED.runtime_minutes,
    omdb_fetched_at = now()
RETURNING id, imdb_id, title, year, poster_url, director, genre, runtime_minutes, omdb_fetched_at, created_at
`

type UpsertFilmParams struct {
	ImdbID         string  `json:"imdb_id"`
	Title          string  `json:"title"`
	Year           *int32  `json:"year"`
	PosterUrl      *string `json:"poster_url"`
	Director       *string `json:"director"`
	Genre          *string `json:"genre"`
	RuntimeMinutes *int32  `json:"runtime_minutes"`
}

func (q *Queries) UpsertFilm(ctx context.Context, arg UpsertFilmParams) (Film, error) {
	row := q.db.QueryRow(ctx, upsertFilm,
		arg.ImdbID,
		arg.Title,
		arg.Year,
		arg.PosterUrl,
		arg.Director,
		arg.Genre,
		arg.RuntimeMinutes,
	)
	var i Film
	err := row.Scan(
		&i.ID,
		&i.ImdbID,
		&i.Title,
		&i.Year,
		&i.PosterUrl,
		&i.Director,
		&i.Genre,
		&i.RuntimeMinutes,
		&i.OmdbFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}
