// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"
	"time"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code, group_id, created_by_user_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, code, group_id, created_by_user_id, expires_at, created_at
`

type CreateInviteParams struct {
	Code            string     `json:"code"`
	GroupID         int32      `json:"group_id"`
	CreatedByUserID int32      `json:"created_by_user_id"`
	ExpiresAt       *time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.Code,
		arg.GroupID,
		arg.CreatedByUserID,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GroupID,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT i.id, i.code, i.group_id, i.expires_at, i.created_at, g.name AS group_name
FROM invites i
JOIN groups g ON g.id = i.group_id
WHERE i.code = $1
`

type GetInviteByCodeRow struct {
	ID        int32      `json:"id"`
	Code      string     `json:"code"`
	GroupID   int32      `json:"group_id"`
	ExpiresAt *time.Time `json:"expires_at"`
	CreatedAt time.Time  `json:"created_at"`
	GroupName string     `json:"group_name"`
}

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (GetInviteByCodeRow, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i GetInviteByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GroupID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.GroupName,
	)
	return i, err
}
