// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMovieByGroupWeek = `-- name: DeleteMovieByGroupWeek :execrows
DELETE FROM movies m
USING turns t
WHERE m.turn_id = t.id AND m.group_id = $1 AND t.week_of = $2
`

type DeleteMovieByGroupWeekParams struct {
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

func (q *Queries) DeleteMovieByGroupWeek(ctx context.Context, arg DeleteMovieByGroupWeekParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMovieByGroupWeek, arg.GroupID, arg.WeekOf)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMovieByGroupWeek = `-- name: GetMovieByGroupWeek :one
SELECT m.id, m.group_id, m.turn_id, m.film_id, m.nominator_user_id, m.created_at,
       t.week_of, t.picker_user_id AS set_by_user_id,
       f.imdb_id, f.title, f.poster_url, f.director, f.genre, f.runtime_minutes, f.year
FROM movies m
JOIN turns t ON t.id = m.turn_id
JOIN films f ON f.id = m.film_id
WHERE m.group_id = $1 AND t.week_of = $2
`

type GetMovieByGroupWeekParams struct {
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

type GetMovieByGroupWeekRow struct {
	ID              int32       `json:"id"`
	GroupID         int32       `json:"group_id"`
	TurnID          int64       `json:"turn_id"`
	FilmID          int64       `json:"film_id"`
	NominatorUserID *int32      `json:"nominator_user_id"`
	CreatedAt       time.Time   `json:"created_at"`
	WeekOf          pgtype.Date `json:"week_of"`
	SetByUserID     int32       `json:"set_by_user_id"`
	ImdbID          string      `json:"imdb_id"`
	Title           string      `json:"title"`
	PosterUrl       *string     `json:"poster_url"`
	Director        *string     `json:"director"`
	Genre           *string     `json:"genre"`
	RuntimeMinutes  *int32      `json:"runtime_minutes"`
	Year            *int32      `json:"year"`
}

func (q *Queries) GetMovieByGroupWeek(ctx context.Context, arg GetMovieByGroupWeekParams) (GetMovieByGroupWeekRow, error) {
	row := q.db.QueryRow(ctx, getMovieByGroupWeek, arg.GroupID, arg.WeekOf)
	var i GetMovieByGroupWeekRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TurnID,
		&i.FilmID,
		&i.NominatorUserID,
		&i.CreatedAt,
		&i.WeekOf,
		&i.SetByUserID,
		&i.ImdbID,
		&i.Title,
		&i.PosterUrl,
		&i.Director,
		&i.Genre,
		&i.RuntimeMinutes,
		&i.Year,
	)
	return i, err
}

const getRecentMoviesWithResults = `-- name: GetRecentMoviesWithResults :many
SELECT m.group_id, g.name AS group_name, f.title AS movie, f.poster_url AS movie_poster, t.week_of,
       COALESCE(AVG(v.rating), 0)::real AS average_rating,
       COUNT(v.id)::int AS total_votes
FROM movies m
JOIN groups g ON g.id = m.group_id
JOIN turns t ON t.id = m.turn_id
JOIN films f ON f.id = m.film_id
JOIN memberships mem ON mem.group_id = m.group_id AND mem.user_id = $1
LEFT JOIN verdicts v ON v.turn_id = t.id
WHERE t.end_date < CURRENT_DATE
GROUP BY m.id, g.name, f.title, f.poster_url, t.week_of
ORDER BY t.week_of DESC
LIMIT $2
`

type GetRecentMoviesWithResultsParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetRecentMoviesWithResultsRow struct {
	GroupID       int32       `json:"group_id"`
	GroupName     string      `json:"group_name"`
	Movie         string      `json:"movie"`
	MoviePoster   *string     `json:"movie_poster"`
	WeekOf        pgtype.Date `json:"week_of"`
	AverageRating float32     `json:"average_rating"`
	TotalVotes    int32       `json:"total_votes"`
}

func (q *Queries) GetRecentMoviesWithResults(ctx context.Context, arg GetRecentMoviesWithResultsParams) ([]GetRecentMoviesWithResultsRow, error) {
	rows, err := q.db.Query(ctx, getRecentMoviesWithResults, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentMoviesWithResultsRow{}
	for rows.Next() {
		var i GetRecentMoviesWithResultsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.Movie,
			&i.MoviePoster,
			&i.WeekOf,
			&i.AverageRating,
			&i.TotalVotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMovie = `-- name: UpsertMovie :one
INSERT INTO movies (group_id, turn_id, film_id, nominator_user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT movies_turn_unique
DO UPDATE SET film_id = EXCLUDED.film_id,
              nominator_user_id = EXCLUDED.nominator_user_id
RETURNING id, group_id, turn_id, film_id, nominator_user_id, created_at
`

type UpsertMovieParams struct {
	GroupID         int32  `json:"group_id"`
	TurnID          int64  `json:"turn_id"`
	FilmID          int64  `json:"film_id"`
	NominatorUserID *int32 `json:"nominator_user_id"`
}

type UpsertMovieRow struct {
	ID              int32     `json:"id"`
	GroupID         int32     `json:"group_id"`
	TurnID          int64     `json:"turn_id"`
	FilmID          int64     `json:"film_id"`
	NominatorUserID *int32    `json:"nominator_user_id"`
	CreatedAt       time.Time `json:"created_at"`
}

func (q *Queries) UpsertMovie(ctx context.Context, arg UpsertMovieParams) (UpsertMovieRow, error) {
	row := q.db.QueryRow(ctx, upsertMovie,
		arg.GroupID,
		arg.TurnID,
		arg.FilmID,
		arg.NominatorUserID,
	)
	var i UpsertMovieRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TurnID,
		&i.FilmID,
		&i.NominatorUserID,
		&i.CreatedAt,
	)
	return i, err
}
