// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package db

import (
	"context"
)

const deleteMovieByGroupWeek = `-- name: DeleteMovieByGroupWeek :execrows
DELETE FROM movies WHERE group_id = $1 AND week_of = $2
`

type DeleteMovieByGroupWeekParams struct {
	GroupID int32  `json:"group_id"`
	WeekOf  string `json:"week_of"`
}

func (q *Queries) DeleteMovieByGroupWeek(ctx context.Context, arg DeleteMovieByGroupWeekParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMovieByGroupWeek, arg.GroupID, arg.WeekOf)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMovieByGroupWeek = `-- name: GetMovieByGroupWeek :one
SELECT id, group_id, title, week_of, set_by_user_id, nominator_user_id, imdb_id, poster, director, genre, runtime, year, created_at
FROM movies
WHERE group_id = $1 AND week_of = $2
`

type GetMovieByGroupWeekParams struct {
	GroupID int32  `json:"group_id"`
	WeekOf  string `json:"week_of"`
}

func (q *Queries) GetMovieByGroupWeek(ctx context.Context, arg GetMovieByGroupWeekParams) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieByGroupWeek, arg.GroupID, arg.WeekOf)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.WeekOf,
		&i.SetByUserID,
		&i.NominatorUserID,
		&i.ImdbID,
		&i.Poster,
		&i.Director,
		&i.Genre,
		&i.Runtime,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentMoviesWithResults = `-- name: GetRecentMoviesWithResults :many
SELECT m.group_id, g.name AS group_name, m.title AS movie, m.week_of,
       COALESCE(AVG(v.rating), 0)::real AS average_rating,
       COUNT(v.id)::int AS total_votes
FROM movies m
JOIN groups g ON g.id = m.group_id
JOIN memberships mem ON mem.group_id = m.group_id AND mem.user_id = $1
LEFT JOIN votes v ON v.group_id = m.group_id AND v.week_of = m.week_of
GROUP BY m.id, g.name
ORDER BY m.week_of DESC
LIMIT $2
`

type GetRecentMoviesWithResultsParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetRecentMoviesWithResultsRow struct {
	GroupID       int32   `json:"group_id"`
	GroupName     string  `json:"group_name"`
	Movie         string  `json:"movie"`
	WeekOf        string  `json:"week_of"`
	AverageRating float32 `json:"average_rating"`
	TotalVotes    int32   `json:"total_votes"`
}

func (q *Queries) GetRecentMoviesWithResults(ctx context.Context, arg GetRecentMoviesWithResultsParams) ([]GetRecentMoviesWithResultsRow, error) {
	rows, err := q.db.Query(ctx, getRecentMoviesWithResults, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentMoviesWithResultsRow{}
	for rows.Next() {
		var i GetRecentMoviesWithResultsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.Movie,
			&i.WeekOf,
			&i.AverageRating,
			&i.TotalVotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMovie = `-- name: UpsertMovie :one
INSERT INTO movies (group_id, title, week_of, set_by_user_id, nominator_user_id, imdb_id, poster, director, genre, runtime, year)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT ON CONSTRAINT movies_group_week_unique
DO UPDATE SET title = EXCLUDED.title,
             set_by_user_id = EXCLUDED.set_by_user_id,
             nominator_user_id = EXCLUDED.nominator_user_id,
             imdb_id = EXCLUDED.imdb_id,
             poster = EXCLUDED.poster,
             director = EXCLUDED.director,
             genre = EXCLUDED.genre,
             runtime = EXCLUDED.runtime,
             year = EXCLUDED.year
RETURNING id, group_id, title, week_of, set_by_user_id, nominator_user_id, imdb_id, poster, director, genre, runtime, year, created_at
`

type UpsertMovieParams struct {
	GroupID         int32   `json:"group_id"`
	Title           string  `json:"title"`
	WeekOf          string  `json:"week_of"`
	SetByUserID     *int32  `json:"set_by_user_id"`
	NominatorUserID *int32  `json:"nominator_user_id"`
	ImdbID          *string `json:"imdb_id"`
	Poster          *string `json:"poster"`
	Director        *string `json:"director"`
	Genre           *string `json:"genre"`
	Runtime         *string `json:"runtime"`
	Year            *string `json:"year"`
}

func (q *Queries) UpsertMovie(ctx context.Context, arg UpsertMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, upsertMovie,
		arg.GroupID,
		arg.Title,
		arg.WeekOf,
		arg.SetByUserID,
		arg.NominatorUserID,
		arg.ImdbID,
		arg.Poster,
		arg.Director,
		arg.Genre,
		arg.Runtime,
		arg.Year,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.WeekOf,
		&i.SetByUserID,
		&i.NominatorUserID,
		&i.ImdbID,
		&i.Poster,
		&i.Director,
		&i.Genre,
		&i.Runtime,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}
