// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nominations.sql

package db

import (
	"context"
	"time"
)

const createNomination = `-- name: CreateNomination :one
INSERT INTO nominations (group_id, user_id, film_id)
VALUES ($1, $2, $3)
RETURNING id, group_id, user_id, film_id, created_at
`

type CreateNominationParams struct {
	GroupID int32 `json:"group_id"`
	UserID  int32 `json:"user_id"`
	FilmID  int64 `json:"film_id"`
}

type CreateNominationRow struct {
	ID        int32     `json:"id"`
	GroupID   int32     `json:"group_id"`
	UserID    int32     `json:"user_id"`
	FilmID    int64     `json:"film_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateNomination(ctx context.Context, arg CreateNominationParams) (CreateNominationRow, error) {
	row := q.db.QueryRow(ctx, createNomination, arg.GroupID, arg.UserID, arg.FilmID)
	var i CreateNominationRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.FilmID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNomination = `-- name: DeleteNomination :exec
DELETE FROM nominations WHERE id = $1
`

func (q *Queries) DeleteNomination(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNomination, id)
	return err
}

const getNominationByGroupAndIMDB = `-- name: GetNominationByGroupAndIMDB :one
SELECT n.id, n.group_id, n.user_id, n.film_id, n.created_at,
       f.imdb_id, f.title, f.year, f.poster_url,
       u.username AS nominator_username
FROM nominations n
JOIN films f ON f.id = n.film_id
JOIN users u ON u.id = n.user_id
WHERE n.group_id = $1 AND f.imdb_id = $2
`

type GetNominationByGroupAndIMDBParams struct {
	GroupID int32  `json:"group_id"`
	ImdbID  string `json:"imdb_id"`
}

type GetNominationByGroupAndIMDBRow struct {
	ID                int32     `json:"id"`
	GroupID           int32     `json:"group_id"`
	UserID            int32     `json:"user_id"`
	FilmID            int64     `json:"film_id"`
	CreatedAt         time.Time `json:"created_at"`
	ImdbID            string    `json:"imdb_id"`
	Title             string    `json:"title"`
	Year              *int32    `json:"year"`
	PosterUrl         *string   `json:"poster_url"`
	NominatorUsername string    `json:"nominator_username"`
}

func (q *Queries) GetNominationByGroupAndIMDB(ctx context.Context, arg GetNominationByGroupAndIMDBParams) (GetNominationByGroupAndIMDBRow, error) {
	row := q.db.QueryRow(ctx, getNominationByGroupAndIMDB, arg.GroupID, arg.ImdbID)
	var i GetNominationByGroupAndIMDBRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.FilmID,
		&i.CreatedAt,
		&i.ImdbID,
		&i.Title,
		&i.Year,
		&i.PosterUrl,
		&i.NominatorUsername,
	)
	return i, err
}

const getNominationByID = `-- name: GetNominationByID :one
SELECT n.id, n.group_id, n.user_id, n.film_id, n.created_at,
       f.imdb_id, f.title, f.year, f.poster_url
FROM nominations n
JOIN films f ON f.id = n.film_id
WHERE n.id = $1
`

type GetNominationByIDRow struct {
	ID        int32     `json:"id"`
	GroupID   int32     `json:"group_id"`
	UserID    int32     `json:"user_id"`
	FilmID    int64     `json:"film_id"`
	CreatedAt time.Time `json:"created_at"`
	ImdbID    string    `json:"imdb_id"`
	Title     string    `json:"title"`
	Year      *int32    `json:"year"`
	PosterUrl *string   `json:"poster_url"`
}

func (q *Queries) GetNominationByID(ctx context.Context, id int32) (GetNominationByIDRow, error) {
	row := q.db.QueryRow(ctx, getNominationByID, id)
	var i GetNominationByIDRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.FilmID,
		&i.CreatedAt,
		&i.ImdbID,
		&i.Title,
		&i.Year,
		&i.PosterUrl,
	)
	return i, err
}

const getNominationsByGroup = `-- name: GetNominationsByGroup :many
SELECT n.id, n.group_id, n.user_id, n.film_id, n.created_at,
       f.imdb_id, f.title, f.year, f.poster_url,
       u.username AS nominator_username
FROM nominations n
JOIN films f ON f.id = n.film_id
JOIN users u ON u.id = n.user_id
WHERE n.group_id = $1
ORDER BY n.created_at DESC
`

type GetNominationsByGroupRow struct {
	ID                int32     `json:"id"`
	GroupID           int32     `json:"group_id"`
	UserID            int32     `json:"user_id"`
	FilmID            int64     `json:"film_id"`
	CreatedAt         time.Time `json:"created_at"`
	ImdbID            string    `json:"imdb_id"`
	Title             string    `json:"title"`
	Year              *int32    `json:"year"`
	PosterUrl         *string   `json:"poster_url"`
	NominatorUsername string    `json:"nominator_username"`
}

func (q *Queries) GetNominationsByGroup(ctx context.Context, groupID int32) ([]GetNominationsByGroupRow, error) {
	rows, err := q.db.Query(ctx, getNominationsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNominationsByGroupRow{}
	for rows.Next() {
		var i GetNominationsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.FilmID,
			&i.CreatedAt,
			&i.ImdbID,
			&i.Title,
			&i.Year,
			&i.PosterUrl,
			&i.NominatorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
