// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stickers.sql

package db

import (
	"context"
)

const countReactionsForSticker = `-- name: CountReactionsForSticker :one
SELECT COUNT(*) FROM reactions WHERE sticker_id = $1
`

func (q *Queries) CountReactionsForSticker(ctx context.Context, stickerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReactionsForSticker, stickerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSticker = `-- name: CreateSticker :one
INSERT INTO stickers (name, image_url, group_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, image_url, group_id, created_by, created_at
`

type CreateStickerParams struct {
	Name      string `json:"name"`
	ImageUrl  string `json:"image_url"`
	GroupID   *int64 `json:"group_id"`
	CreatedBy int32  `json:"created_by"`
}

func (q *Queries) CreateSticker(ctx context.Context, arg CreateStickerParams) (Sticker, error) {
	row := q.db.QueryRow(ctx, createSticker,
		arg.Name,
		arg.ImageUrl,
		arg.GroupID,
		arg.CreatedBy,
	)
	var i Sticker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.GroupID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSticker = `-- name: DeleteSticker :exec
DELETE FROM stickers
WHERE id = $1
`

func (q *Queries) DeleteSticker(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSticker, id)
	return err
}

const deleteStickerIfOwned = `-- name: DeleteStickerIfOwned :execrows
DELETE FROM stickers
WHERE id = $1 AND (group_id IS NULL OR group_id = $2)
`

type DeleteStickerIfOwnedParams struct {
	ID      int64  `json:"id"`
	GroupID *int64 `json:"group_id"`
}

func (q *Queries) DeleteStickerIfOwned(ctx context.Context, arg DeleteStickerIfOwnedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStickerIfOwned, arg.ID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGlobalStickers = `-- name: GetGlobalStickers :many
SELECT id, name, image_url, group_id, created_by, created_at
FROM stickers
WHERE group_id IS NULL
ORDER BY created_at
`

func (q *Queries) GetGlobalStickers(ctx context.Context) ([]Sticker, error) {
	rows, err := q.db.Query(ctx, getGlobalStickers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sticker{}
	for rows.Next() {
		var i Sticker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.GroupID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupStickers = `-- name: GetGroupStickers :many
SELECT id, name, image_url, group_id, created_by, created_at
FROM stickers
WHERE group_id = $1
ORDER BY created_at
`

func (q *Queries) GetGroupStickers(ctx context.Context, groupID *int64) ([]Sticker, error) {
	rows, err := q.db.Query(ctx, getGroupStickers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sticker{}
	for rows.Next() {
		var i Sticker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.GroupID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStickerByID = `-- name: GetStickerByID :one
SELECT id, name, image_url, group_id, created_by, created_at
FROM stickers
WHERE id = $1
`

func (q *Queries) GetStickerByID(ctx context.Context, id int64) (Sticker, error) {
	row := q.db.QueryRow(ctx, getStickerByID, id)
	var i Sticker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.GroupID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getStickersForGroup = `-- name: GetStickersForGroup :many
SELECT id, name, image_url, group_id, created_by, created_at
FROM stickers
WHERE group_id IS NULL OR group_id = $1
ORDER BY group_id NULLS FIRST, created_at
`

func (q *Queries) GetStickersForGroup(ctx context.Context, groupID *int64) ([]Sticker, error) {
	rows, err := q.db.Query(ctx, getStickersForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sticker{}
	for rows.Next() {
		var i Sticker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.GroupID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
