// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: turns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTurn = `-- name: CreateTurn :one
INSERT INTO turns (
    group_id, turn_index, week_of, picker_user_id, start_date, end_date,
    movie_unlocked, reviews_unlocked
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, group_id, turn_index, week_of, picker_user_id, start_date, end_date,
          movie_unlocked, reviews_unlocked, created_at, updated_at
`

type CreateTurnParams struct {
	GroupID         int32       `json:"group_id"`
	TurnIndex       int32       `json:"turn_index"`
	WeekOf          pgtype.Date `json:"week_of"`
	PickerUserID    int32       `json:"picker_user_id"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	MovieUnlocked   bool        `json:"movie_unlocked"`
	ReviewsUnlocked bool        `json:"reviews_unlocked"`
}

func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, createTurn,
		arg.GroupID,
		arg.TurnIndex,
		arg.WeekOf,
		arg.PickerUserID,
		arg.StartDate,
		arg.EndDate,
		arg.MovieUnlocked,
		arg.ReviewsUnlocked,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TurnIndex,
		&i.WeekOf,
		&i.PickerUserID,
		&i.StartDate,
		&i.EndDate,
		&i.MovieUnlocked,
		&i.ReviewsUnlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTurn = `-- name: DeleteTurn :exec
DELETE FROM turns WHERE id = $1
`

func (q *Queries) DeleteTurn(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTurn, id)
	return err
}

const extendTurn = `-- name: ExtendTurn :exec
UPDATE turns
SET end_date = end_date + ($2 * INTERVAL '1 day'), updated_at = now()
WHERE id = $1
`

type ExtendTurnParams struct {
	ID      int64       `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) ExtendTurn(ctx context.Context, arg ExtendTurnParams) error {
	_, err := q.db.Exec(ctx, extendTurn, arg.ID, arg.Column2)
	return err
}

const getCurrentTurn = `-- name: GetCurrentTurn :one
SELECT id, group_id, turn_index, week_of, picker_user_id, start_date, end_date,
       movie_unlocked, reviews_unlocked, created_at, updated_at
FROM turns
WHERE group_id = $1 AND start_date <= CURRENT_DATE AND end_date >= CURRENT_DATE
LIMIT 1
`

func (q *Queries) GetCurrentTurn(ctx context.Context, groupID int32) (Turn, error) {
	row := q.db.QueryRow(ctx, getCurrentTurn, groupID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TurnIndex,
		&i.WeekOf,
		&i.PickerUserID,
		&i.StartDate,
		&i.EndDate,
		&i.MovieUnlocked,
		&i.ReviewsUnlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestTurnForGroup = `-- name: GetLatestTurnForGroup :one
SELECT id, group_id, turn_index, week_of, picker_user_id, start_date, end_date,
       movie_unlocked, reviews_unlocked, created_at, updated_at
FROM turns
WHERE group_id = $1
ORDER BY turn_index DESC
LIMIT 1
`

func (q *Queries) GetLatestTurnForGroup(ctx context.Context, groupID int32) (Turn, error) {
	row := q.db.QueryRow(ctx, getLatestTurnForGroup, groupID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TurnIndex,
		&i.WeekOf,
		&i.PickerUserID,
		&i.StartDate,
		&i.EndDate,
		&i.MovieUnlocked,
		&i.ReviewsUnlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurn = `-- name: GetTurn :one
SELECT id, group_id, turn_index, week_of, picker_user_id, start_date, end_date,
       movie_unlocked, reviews_unlocked, created_at, updated_at
FROM turns
WHERE group_id = $1 AND week_of = $2
`

type GetTurnParams struct {
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

func (q *Queries) GetTurn(ctx context.Context, arg GetTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurn, arg.GroupID, arg.WeekOf)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TurnIndex,
		&i.WeekOf,
		&i.PickerUserID,
		&i.StartDate,
		&i.EndDate,
		&i.MovieUnlocked,
		&i.ReviewsUnlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurnByID = `-- name: GetTurnByID :one
SELECT id, group_id, turn_index, week_of, picker_user_id, start_date, end_date,
       movie_unlocked, reviews_unlocked, created_at, updated_at
FROM turns
WHERE id = $1
`

func (q *Queries) GetTurnByID(ctx context.Context, id int64) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurnByID, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TurnIndex,
		&i.WeekOf,
		&i.PickerUserID,
		&i.StartDate,
		&i.EndDate,
		&i.MovieUnlocked,
		&i.ReviewsUnlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurnByIndex = `-- name: GetTurnByIndex :one
SELECT id, group_id, turn_index, week_of, picker_user_id, start_date, end_date,
       movie_unlocked, reviews_unlocked, created_at, updated_at
FROM turns
WHERE group_id = $1 AND turn_index = $2
`

type GetTurnByIndexParams struct {
	GroupID   int32 `json:"group_id"`
	TurnIndex int32 `json:"turn_index"`
}

func (q *Queries) GetTurnByIndex(ctx context.Context, arg GetTurnByIndexParams) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurnByIndex, arg.GroupID, arg.TurnIndex)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TurnIndex,
		&i.WeekOf,
		&i.PickerUserID,
		&i.StartDate,
		&i.EndDate,
		&i.MovieUnlocked,
		&i.ReviewsUnlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurnsForGroup = `-- name: GetTurnsForGroup :many
SELECT id, group_id, turn_index, week_of, picker_user_id, start_date, end_date,
       movie_unlocked, reviews_unlocked, created_at, updated_at
FROM turns
WHERE group_id = $1
ORDER BY turn_index
`

func (q *Queries) GetTurnsForGroup(ctx context.Context, groupID int32) ([]Turn, error) {
	rows, err := q.db.Query(ctx, getTurnsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Turn{}
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.TurnIndex,
			&i.WeekOf,
			&i.PickerUserID,
			&i.StartDate,
			&i.EndDate,
			&i.MovieUnlocked,
			&i.ReviewsUnlocked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTurnDates = `-- name: UpdateTurnDates :exec
UPDATE turns
SET start_date = $2, end_date = $3, updated_at = now()
WHERE id = $1
`

type UpdateTurnDatesParams struct {
	ID        int64       `json:"id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateTurnDates(ctx context.Context, arg UpdateTurnDatesParams) error {
	_, err := q.db.Exec(ctx, updateTurnDates, arg.ID, arg.StartDate, arg.EndDate)
	return err
}

const updateTurnMovieUnlocked = `-- name: UpdateTurnMovieUnlocked :exec
UPDATE turns
SET movie_unlocked = $2, updated_at = now()
WHERE id = $1
`

type UpdateTurnMovieUnlockedParams struct {
	ID            int64 `json:"id"`
	MovieUnlocked bool  `json:"movie_unlocked"`
}

func (q *Queries) UpdateTurnMovieUnlocked(ctx context.Context, arg UpdateTurnMovieUnlockedParams) error {
	_, err := q.db.Exec(ctx, updateTurnMovieUnlocked, arg.ID, arg.MovieUnlocked)
	return err
}

const updateTurnPicker = `-- name: UpdateTurnPicker :exec
UPDATE turns
SET picker_user_id = $2, updated_at = now()
WHERE id = $1
`

type UpdateTurnPickerParams struct {
	ID           int64 `json:"id"`
	PickerUserID int32 `json:"picker_user_id"`
}

func (q *Queries) UpdateTurnPicker(ctx context.Context, arg UpdateTurnPickerParams) error {
	_, err := q.db.Exec(ctx, updateTurnPicker, arg.ID, arg.PickerUserID)
	return err
}

const updateTurnReviewsUnlocked = `-- name: UpdateTurnReviewsUnlocked :exec
UPDATE turns
SET reviews_unlocked = $2, updated_at = now()
WHERE id = $1
`

type UpdateTurnReviewsUnlockedParams struct {
	ID              int64 `json:"id"`
	ReviewsUnlocked bool  `json:"reviews_unlocked"`
}

func (q *Queries) UpdateTurnReviewsUnlocked(ctx context.Context, arg UpdateTurnReviewsUnlockedParams) error {
	_, err := q.db.Exec(ctx, updateTurnReviewsUnlocked, arg.ID, arg.ReviewsUnlocked)
	return err
}

const upsertTurn = `-- name: UpsertTurn :one
INSERT INTO turns (
    group_id, turn_index, week_of, picker_user_id, start_date, end_date,
    movie_unlocked, reviews_unlocked
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT ON CONSTRAINT turns_group_index_unique
DO UPDATE SET
    week_of = EXCLUDED.week_of,
    picker_user_id = EXCLUDED.picker_user_id,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    movie_unlocked = EXCLUDED.movie_unlocked,
    reviews_unlocked = EXCLUDED.reviews_unlocked,
    updated_at = now()
RETURNING id, group_id, turn_index, week_of, picker_user_id, start_date, end_date,
          movie_unlocked, reviews_unlocked, created_at, updated_at
`

type UpsertTurnParams struct {
	GroupID         int32       `json:"group_id"`
	TurnIndex       int32       `json:"turn_index"`
	WeekOf          pgtype.Date `json:"week_of"`
	PickerUserID    int32       `json:"picker_user_id"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	MovieUnlocked   bool        `json:"movie_unlocked"`
	ReviewsUnlocked bool        `json:"reviews_unlocked"`
}

func (q *Queries) UpsertTurn(ctx context.Context, arg UpsertTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, upsertTurn,
		arg.GroupID,
		arg.TurnIndex,
		arg.WeekOf,
		arg.PickerUserID,
		arg.StartDate,
		arg.EndDate,
		arg.MovieUnlocked,
		arg.ReviewsUnlocked,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TurnIndex,
		&i.WeekOf,
		&i.PickerUserID,
		&i.StartDate,
		&i.EndDate,
		&i.MovieUnlocked,
		&i.ReviewsUnlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
