// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verdict_replies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerdictReply = `-- name: CreateVerdictReply :one
INSERT INTO verdict_replies (verdict_id, user_id, body)
VALUES ($1, $2, $3)
RETURNING id, verdict_id, user_id, body, created_at, updated_at
`

type CreateVerdictReplyParams struct {
	VerdictID int64  `json:"verdict_id"`
	UserID    int32  `json:"user_id"`
	Body      string `json:"body"`
}

func (q *Queries) CreateVerdictReply(ctx context.Context, arg CreateVerdictReplyParams) (VerdictReply, error) {
	row := q.db.QueryRow(ctx, createVerdictReply, arg.VerdictID, arg.UserID, arg.Body)
	var i VerdictReply
	err := row.Scan(
		&i.ID,
		&i.VerdictID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerdictReplyByID = `-- name: GetVerdictReplyByID :one
SELECT id, verdict_id, user_id, body, created_at, updated_at
FROM verdict_replies
WHERE id = $1
`

func (q *Queries) GetVerdictReplyByID(ctx context.Context, id int64) (VerdictReply, error) {
	row := q.db.QueryRow(ctx, getVerdictReplyByID, id)
	var i VerdictReply
	err := row.Scan(
		&i.ID,
		&i.VerdictID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepliesForVerdicts = `-- name: GetRepliesForVerdicts :many
SELECT vr.id, vr.verdict_id, vr.user_id, vr.body, vr.created_at, vr.updated_at,
       u.username, u.avatar_url
FROM verdict_replies vr
JOIN users u ON u.id = vr.user_id
WHERE vr.verdict_id = ANY($1::bigint[])
ORDER BY vr.created_at
`

type GetRepliesForVerdictsRow struct {
	ID        int64              `json:"id"`
	VerdictID int64              `json:"verdict_id"`
	UserID    int32              `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Username  string             `json:"username"`
	AvatarUrl *string            `json:"avatar_url"`
}

func (q *Queries) GetRepliesForVerdicts(ctx context.Context, verdictIds []int64) ([]GetRepliesForVerdictsRow, error) {
	rows, err := q.db.Query(ctx, getRepliesForVerdicts, verdictIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRepliesForVerdictsRow{}
	for rows.Next() {
		var i GetRepliesForVerdictsRow
		if err := rows.Scan(
			&i.ID,
			&i.VerdictID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
