// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: votes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVote = `-- name: DeleteVote :exec
UPDATE verdicts
SET rating = NULL, review = NULL, updated_at = now()
WHERE user_id = $1
  AND turn_id = (
    SELECT id FROM turns
    WHERE group_id = $2 AND week_of = $3::date
  )
`

type DeleteVoteParams struct {
	UserID  int32       `json:"user_id"`
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

func (q *Queries) DeleteVote(ctx context.Context, arg DeleteVoteParams) error {
	_, err := q.db.Exec(ctx, deleteVote, arg.UserID, arg.GroupID, arg.WeekOf)
	return err
}

const getUserVote = `-- name: GetUserVote :one
SELECT v.rating::real AS rating, v.review
FROM verdicts v
JOIN turns t ON t.id = v.turn_id
WHERE v.user_id = $1
  AND t.group_id = $2
  AND t.week_of = $3::date
  AND v.rating IS NOT NULL
`

type GetUserVoteParams struct {
	UserID  int32       `json:"user_id"`
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

type GetUserVoteRow struct {
	Rating float32 `json:"rating"`
	Review *string `json:"review"`
}

func (q *Queries) GetUserVote(ctx context.Context, arg GetUserVoteParams) (GetUserVoteRow, error) {
	row := q.db.QueryRow(ctx, getUserVote, arg.UserID, arg.GroupID, arg.WeekOf)
	var i GetUserVoteRow
	err := row.Scan(&i.Rating, &i.Review)
	return i, err
}

const getVotesForGroupWeek = `-- name: GetVotesForGroupWeek :many
SELECT v.user_id,
       u.username,
       v.rating::real AS rating,
       v.review,
       to_char(t.week_of, 'YYYY-MM-DD') AS week_of,
       v.updated_at
FROM verdicts v
JOIN turns t ON t.id = v.turn_id
JOIN users u ON u.id = v.user_id
WHERE t.group_id = $1
  AND t.week_of = $2::date
  AND v.rating IS NOT NULL
ORDER BY v.created_at
`

type GetVotesForGroupWeekParams struct {
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

type GetVotesForGroupWeekRow struct {
	UserID    int32              `json:"user_id"`
	Username  string             `json:"username"`
	Rating    float32            `json:"rating"`
	Review    *string            `json:"review"`
	WeekOf    string             `json:"week_of"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVotesForGroupWeek(ctx context.Context, arg GetVotesForGroupWeekParams) ([]GetVotesForGroupWeekRow, error) {
	rows, err := q.db.Query(ctx, getVotesForGroupWeek, arg.GroupID, arg.WeekOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVotesForGroupWeekRow{}
	for rows.Next() {
		var i GetVotesForGroupWeekRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Rating,
			&i.Review,
			&i.WeekOf,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserVoted = `-- name: HasUserVoted :one
SELECT EXISTS(
    SELECT 1 FROM verdicts v
    JOIN turns t ON t.id = v.turn_id
    WHERE v.user_id = $1
      AND t.group_id = $2
      AND t.week_of = $3::date
      AND v.rating IS NOT NULL
) AS has_voted
`

type HasUserVotedParams struct {
	UserID  int32       `json:"user_id"`
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

func (q *Queries) HasUserVoted(ctx context.Context, arg HasUserVotedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserVoted, arg.UserID, arg.GroupID, arg.WeekOf)
	var has_voted bool
	err := row.Scan(&has_voted)
	return has_voted, err
}

const upsertVote = `-- name: UpsertVote :exec

INSERT INTO verdicts (turn_id, user_id, watched, rating, review)
SELECT t.id,
       $1::int,
       true,
       $2::numeric,
       $3
FROM turns t
WHERE t.group_id = $4 AND t.week_of = $5::date
ON CONFLICT ON CONSTRAINT verdicts_turn_user_unique
DO UPDATE SET rating = EXCLUDED.rating,
              review = EXCLUDED.review,
              watched = true,
              updated_at = now()
`

type UpsertVoteParams struct {
	UserID  int32          `json:"user_id"`
	Rating  pgtype.Numeric `json:"rating"`
	Review  *string        `json:"review"`
	GroupID int32          `json:"group_id"`
	WeekOf  pgtype.Date    `json:"week_of"`
}

// Vote queries are thin views over the canonical verdicts table.
// A "vote" is a verdict with a non-null rating; the deprecated votes
// table no longer exists.
func (q *Queries) UpsertVote(ctx context.Context, arg UpsertVoteParams) error {
	_, err := q.db.Exec(ctx, upsertVote,
		arg.UserID,
		arg.Rating,
		arg.Review,
		arg.GroupID,
		arg.WeekOf,
	)
	return err
}
