// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchstatus.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWatchStatuses = `-- name: GetWatchStatuses :many
SELECT v.user_id,
       t.group_id,
       to_char(t.week_of, 'YYYY-MM-DD') AS week_of,
       v.watched
FROM verdicts v
JOIN turns t ON t.id = v.turn_id
WHERE t.group_id = $1
  AND t.week_of = $2::date
`

type GetWatchStatusesParams struct {
	GroupID int32       `json:"group_id"`
	WeekOf  pgtype.Date `json:"week_of"`
}

type GetWatchStatusesRow struct {
	UserID  int32  `json:"user_id"`
	GroupID int32  `json:"group_id"`
	WeekOf  string `json:"week_of"`
	Watched bool   `json:"watched"`
}

func (q *Queries) GetWatchStatuses(ctx context.Context, arg GetWatchStatusesParams) ([]GetWatchStatusesRow, error) {
	rows, err := q.db.Query(ctx, getWatchStatuses, arg.GroupID, arg.WeekOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWatchStatusesRow{}
	for rows.Next() {
		var i GetWatchStatusesRow
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.WeekOf,
			&i.Watched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
