// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchstatus.sql

package db

import (
	"context"
)

const getWatchStatuses = `-- name: GetWatchStatuses :many
SELECT user_id, group_id, week_of, watched
FROM _deprecated_watch_status
WHERE group_id = $1 AND week_of = $2
`

type GetWatchStatusesParams struct {
	GroupID int32  `json:"group_id"`
	WeekOf  string `json:"week_of"`
}

type GetWatchStatusesRow struct {
	UserID  int32  `json:"user_id"`
	GroupID int32  `json:"group_id"`
	WeekOf  string `json:"week_of"`
	Watched bool   `json:"watched"`
}

func (q *Queries) GetWatchStatuses(ctx context.Context, arg GetWatchStatusesParams) ([]GetWatchStatusesRow, error) {
	rows, err := q.db.Query(ctx, getWatchStatuses, arg.GroupID, arg.WeekOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWatchStatusesRow{}
	for rows.Next() {
		var i GetWatchStatusesRow
		if err := rows.Scan(
			&i.UserID,
			&i.GroupID,
			&i.WeekOf,
			&i.Watched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWatchStatus = `-- name: UpsertWatchStatus :exec
INSERT INTO _deprecated_watch_status (user_id, group_id, week_of, watched)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT _deprecated_watch_status_user_group_week
DO UPDATE SET watched = EXCLUDED.watched, updated_at = now()
`

type UpsertWatchStatusParams struct {
	UserID  int32  `json:"user_id"`
	GroupID int32  `json:"group_id"`
	WeekOf  string `json:"week_of"`
	Watched bool   `json:"watched"`
}

func (q *Queries) UpsertWatchStatus(ctx context.Context, arg UpsertWatchStatusParams) error {
	_, err := q.db.Exec(ctx, upsertWatchStatus,
		arg.UserID,
		arg.GroupID,
		arg.WeekOf,
		arg.Watched,
	)
	return err
}
